### ISSUE TITLE
One or more frames of complete black appear when starting playtesting / bringing up a menu

### ISSUE THREAD

**Issue by InfoTeddy** [Colon-D/VVVVVV-over-30-FPS#2]
I've found at least four places where a random frame of black appears for a few frames or two:

 - When starting to playtest in the editor by pressing Enter
 - When pressing Enter, _not_ at a teleporter, to bring up the pause screen
 - When pressing Esc to bring up the quit screen
 - When pressing Enter at a teleporter to bring up the teleporter screen

**Comment by Colon-D** [comment]
This has been fixed.

In the original game, the screen buffers are flipped at a fixed framerate.

The modded game this worked by:
If the gamestate was NOT gameplay flip at a fixed framerate
If the gamestate IS gameplay flip at variable framerate

When switching from gameplay to non-gameplay, the fixed framerate screen buffer flip was being called, and since the fixed gameplay render function does not actually render anything now (it just updates variables), the screen buffer was blank.

I have now created a variable that is set to the current gamestate before input is processed, this variable is now checked when calling the screen buffer flip function instead.
