### ISSUE TITLE
Warp backgrounds of rooms do not animate while in the editor

### ISSUE THREAD

**Issue by InfoTeddy** [Colon-D/VVVVVV-over-30-FPS#4]
They stand still and are static and unchanging, compared to their having animation in the original game.

**Comment by Colon-D** [comment]
This has been fixed.

In the original game, the horizontal and vertical warp backgrounds moved at 3 pixels per frame, the central warp background moved at 1 pixel per frame.

In the modded game this used deltatime, so that the horizontal and vertical warp backgrounds were meant to move at 3 pixels per 1/30th of a second, and the central warp background moved at 1 pixel per 1/30th of a second.

Rereading my code, inside the background update code I used a division instead of a multiplication when calculating the new speed per second which replaced the speed per frame, and inside gameplay the deltatime calculated was in milliseconds not seconds, and the editor deltatime calculation was wrong as well because I used a bad equation. That's a lot of mistakes, whoops, sorry.

It just so happened that all the mistakes resulted in roughly similar results as the expected results for gameplay (but the results were wrong because the math was wrong, they were 10% too fast).
As for the editor, it was passing in roughly the right time, but not actually because my math was bad, the amount of seconds that had passed, and when passing in seconds to my wrong previous equations instead of milliseconds it resulted in a background moving at 0.003 pixels per frame.

The math has been changed, to be a multiplication instead of division, and also to be relative to 1000/34fps because as far as I can tell, technically the original game doesn't run at 30fps, it runs at 1000/34fps. If updating at 30 then the background is 2% too fast.

During gameplay, deltatime passed in is now in seconds like intended instead of milliseconds.

Overall, all backgrounds now update at 88% of the speed they were going at during gameplay, and the background update at a much higher speed than the speed that they were going at during the editor.

This is the only thing that uses deltatime now, and since it is purely visual (unlike the fading bars (I hope)), this should be fine using deltatime.
